spring:
  application:
    name: kafka-logstash
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
logging:
  config: classpath:logback-spring.xml

server:
  port: 8080
  servlet:
    context-path: /